name: Lint With Stylua
on:
  push:
    branches:
      - main
jobs:
  test_default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: linting with Stylua"
