name: Check Lint With Stylua
on:
  pull_request:
    paths:
      - "**.lua"
jobs:
  format_code:
    if: github.repository == 'aarondill/wezterm'
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
